<a href="https://colab.research.google.com/github/NiGHtFUry0000/testrepo/blob/matesr/data_science_usng_genrative_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
# prompt: import all the librarys for classsification problem

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [45]:
# prompt: create a data using  path /content/adult.data

import pandas as pd
# Load the data from the specified path
data = pd.read_csv('/content/adult.data', header=None)

# Assign column names to the data
data.columns = ['age', 'workclass', 'fnlwgt', 'education', 'education-num',
               'marital-status', 'occupation', 'relationship', 'race', 'sex',
               'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'salary']

# Display the data
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [46]:
# prompt: unique values in data

# Get unique values for each column
unique_values = {}
for column in data.columns:
  unique_values[column] = data[column].unique()

# Print the unique values
for column, values in unique_values.items():
  print(f"Unique values for column '{column}': {values}")

Unique values for column 'age': [39 50 38 53 28 37 49 52 31 42 30 23 32 40 34 25 43 54 35 59 56 19 20 45
 22 48 21 24 57 44 41 29 18 47 46 36 79 27 67 33 76 17 55 61 70 64 71 68
 66 51 58 26 60 90 75 65 77 62 63 80 72 74 69 73 81 78 88 82 83 84 85 86
 87]
Unique values for column 'workclass': [' State-gov' ' Self-emp-not-inc' ' Private' ' Federal-gov' ' Local-gov'
 ' ?' ' Self-emp-inc' ' Without-pay' ' Never-worked']
Unique values for column 'fnlwgt': [ 77516  83311 215646 ...  34066  84661 257302]
Unique values for column 'education': [' Bachelors' ' HS-grad' ' 11th' ' Masters' ' 9th' ' Some-college'
 ' Assoc-acdm' ' Assoc-voc' ' 7th-8th' ' Doctorate' ' Prof-school'
 ' 5th-6th' ' 10th' ' 1st-4th' ' Preschool' ' 12th']
Unique values for column 'education-num': [13  9  7 14  5 10 12 11  4 16 15  3  6  2  1  8]
Unique values for column 'marital-status': [' Never-married' ' Married-civ-spouse' ' Divorced'
 ' Married-spouse-absent' ' Separated' ' Married-AF-spouse' ' Widowed']
Unique values for column 'occupation': [' Adm-clerical' ' Exec-managerial' ' Handlers-cleaners' ' Prof-specialty'
 ' Other-service' ' Sales' ' Craft-repair' ' Transport-moving'
 ' Farming-fishing' ' Machine-op-inspct' ' Tech-support' ' ?'
 ' Protective-serv' ' Armed-Forces' ' Priv-house-serv']
Unique values for column 'relationship': [' Not-in-family' ' Husband' ' Wife' ' Own-child' ' Unmarried'
 ' Other-relative']
Unique values for column 'race': [' White' ' Black' ' Asian-Pac-Islander' ' Amer-Indian-Eskimo' ' Other']
Unique values for column 'sex': [' Male' ' Female']
Unique values for column 'capital-gain': [ 2174     0 14084  5178  5013  2407 14344 15024  7688 34095  4064  4386
  7298  1409  3674  1055  3464  2050  2176   594 20051  6849  4101  1111
  8614  3411  2597 25236  4650  9386  2463  3103 10605  2964  3325  2580
  3471  4865 99999  6514  1471  2329  2105  2885 25124 10520  2202  2961
 27828  6767  2228  1506 13550  2635  5556  4787  3781  3137  3818  3942
   914   401  2829  2977  4934  2062  2354  5455 15020  1424  3273 22040
  4416  3908 10566   991  4931  1086  7430  6497   114  7896  2346  3418
  3432  2907  1151  2414  2290 15831 41310  4508  2538  3456  6418  1848
  3887  5721  9562  1455  2036  1831 11678  2936  2993  7443  6360  1797
  1173  4687  6723  2009  6097  2653  1639 18481  7978  2387  5060]
Unique values for column 'capital-loss': [   0 2042 1408 1902 1573 1887 1719 1762 1564 2179 1816 1980 1977 1876
 1340 2206 1741 1485 2339 2415 1380 1721 2051 2377 1669 2352 1672  653
 2392 1504 2001 1590 1651 1628 1848 1740 2002 1579 2258 1602  419 2547
 2174 2205 1726 2444 1138 2238  625  213 1539  880 1668 1092 1594 3004
 2231 1844  810 2824 2559 2057 1974  974 2149 1825 1735 1258 2129 2603
 2282  323 4356 2246 1617 1648 2489 3770 1755 3683 2267 2080 2457  155
 3900 2201 1944 2467 2163 2754 2472 1411]
Unique values for column 'hours-per-week': [40 13 16 45 50 80 30 35 60 20 52 44 15 25 38 43 55 48 58 32 70  2 22 56
 41 28 36 24 46 42 12 65  1 10 34 75 98 33 54  8  6 64 19 18 72  5  9 47
 37 21 26 14  4 59  7 99 53 39 62 57 78 90 66 11 49 84  3 17 68 27 85 31
 51 77 63 23 87 88 73 89 97 94 29 96 67 82 86 91 81 76 92 61 74 95]
Unique values for column 'native-country': [' United-States' ' Cuba' ' Jamaica' ' India' ' ?' ' Mexico' ' South'
 ' Puerto-Rico' ' Honduras' ' England' ' Canada' ' Germany' ' Iran'
 ' Philippines' ' Italy' ' Poland' ' Columbia' ' Cambodia' ' Thailand'
 ' Ecuador' ' Laos' ' Taiwan' ' Haiti' ' Portugal' ' Dominican-Republic'
 ' El-Salvador' ' France' ' Guatemala' ' China' ' Japan' ' Yugoslavia'
 ' Peru' ' Outlying-US(Guam-USVI-etc)' ' Scotland' ' Trinadad&Tobago'
 ' Greece' ' Nicaragua' ' Vietnam' ' Hong' ' Ireland' ' Hungary'
 ' Holand-Netherlands']
Unique values for column 'salary': [' <=50K' ' >50K']

In [48]:
# prompt: as df contians nan values as ? convert it into  numpy nan


# Replace '?' with numpy nan
data = data.replace('?', np.nan)

In [49]:
# prompt: drop all the null values

data = data.dropna()

In [50]:
df.describe()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
count,30162.000000,30162.000000,30162.000000,30162.000000,30162.000000,30162.000000,30162.000000,30162.000000,30162.000000,30162.000000,30162.000000,30162.000000,30162.000000,30162.000000,30162.000000
mean,0.293670,0.366554,0.119669,0.688918,0.608087,0.430022,0.458450,0.283668,0.919651,0.675685,0.010920,0.020288,0.407462,0.909564,0.248922
std,0.179927,0.158987,0.071827,0.254153,0.170000,0.249669,0.309967,0.320268,0.208677,0.468126,0.074064,0.092814,0.122245,0.152634,0.432396
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.150685,0.333333,0.070607,0.600000,0.533333,0.333333,0.153846,0.000000,1.000000,0.000000,0.000000,0.000000,0.397959,0.950000,0.000000
50%,0.273973,0.333333,0.111940,0.733333,0.600000,0.333333,0.461538,0.200000,1.000000,1.000000,0.000000,0.000000,0.397959,0.950000,0.000000
75%,0.410959,0.333333,0.152188,0.800000,0.800000,0.666667,0.692308,0.600000,1.000000,1.000000,0.000000,0.000000,0.448980,0.950000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [51]:
# prompt: create seprate encoder for each catgorical data  also save that for future use

from sklearn.preprocessing import LabelEncoder

# Create a label encoder for each categorical column
encoders = {}
for column in data.select_dtypes(include=["object"]):
  encoders[column] = LabelEncoder()
  encoders[column].fit(data[column])

# Save the encoders for future use
import pickle
with open('encoders.pkl', 'wb') as f:
  pickle.dump(encoders, f)

# Encode the categorical columns
for column, encoder in encoders.items():
  data[column] = encoder.transform(data[column])

In [60]:
# prompt: perfrom feature scaling

from sklearn.preprocessing import StandardScaler

# Create a standard scaler
scaler = StandardScaler()

# Fit the scaler to the data
scaler.fit(data)

# Transform the data
data = scaler.transform(data)

# Save the scaler for future use
with open('scaler.pkl', 'wb') as f:
  pickle.dump(scaler, f)

In [57]:
# prompt: split data intarain test split 80 20

X = data.drop('salary', axis=1)
y = data['salary']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training set size:", X_train.shape[0])
print("Test set size:", X_test.shape[0])

Shape of X_train: (24420, 14)
Shape of X_test: (8141, 14)
Shape of y_train: (24420,)
Shape of y_test: (8141,)

In [62]:
# prompt: make multipule calssfication models

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

# Define multiple classification models
models = {
    "Logistic Regression": LogisticRegression(),
    "Random Forest": RandomForestClassifier(),
    "SVM": SVC(),
    "KNN": KNeighborsClassifier()
}

# Train each model
for name, model in models.items():
    model.fit(X_train, y_train)
    print(f"{name} model trained successfully.")

# Save each model
for name, model in models.items():
    with open(f"{name}.pkl", "wb") as f:
        pickle.dump(model, f)
    print(f"{name} model saved successfully.")

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression model trained successfully.
Random Forest model trained successfully.
SVM model trained successfully.
KNN model trained successfully.
Logistic Regression model saved successfully.
Random Forest model saved successfully.
SVM model saved successfully.
KNN model saved successfully.

In [63]:
# prompt: accuracy of each model

# Evaluate each model
for name, model in models.items():
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"{name} accuracy: {accuracy}")

Logistic Regression accuracy: 0.7941284854440487
Random Forest accuracy: 0.8616877533472547
SVM accuracy: 0.7994103918437538
KNN accuracy: 0.7763174057241126

In [ ]:
# prompt: perform hyper parameter tunig on subset of random forest random forest

from sklearn.model_selection import GridSearchCV

# Define the grid of hyperparameters to search
param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [5, 10, 15],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Create a Random Forest classifier instance
rf = RandomForestClassifier()

# Instantiate the GridSearchCV object
grid_search = GridSearchCV(rf, param_grid, cv=5)

# Fit the grid search object to the training data
grid_search.fit(X_train, y_train)

# Get the best set of hyperparameters
best_params = grid_search.best_params_

# Print the best hyperparameters
print("Best hyperparameters:", best_params)

# Get the best model
best_model = grid_search.best_estimator_

# Save the best model
with open("best_random_forest.pkl", "wb") as f:
    pickle.dump(best_model, f)

# Evaluate the best model on the test data
y_pred = best_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Best model accuracy: {accuracy}")